baseURL = 'https://kevinamparado.com/'
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Kevin Amparado"
author = "Kevin Amparado"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
  email = "hello@kevinamparado.com"

  # The "description" of your website. This is used in the meta data of your generated html.
  description = "no fuzz, straight to the point info & blog about Kevin Amparado, built using hugo bear"

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Kevin Amparado"

[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.highlight]
    style = "gruvbox"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

  [markup.goldmark.renderer]
  unsafe = true

[menus]
  [[menus.social]]
    name = "github"
    url = "https://github.com/KevsterAmp"
    weight = 20

  [[menus.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kevin-amparado/"
    weight = 30

