baseURL = 'https://kevinamparado.com/'
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Kevin Amparado"
author = "Kevin Amparado"
languageCode = "en-US"

[params]
  email = "hello@kevinamparado.com"

[markup]
  defaultMarkdownHandler = 'goldmark'

  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true

[markup.goldmark.renderer]
unsafe = true

[menus]
  [[menus.social]]
    name = "github"
    url = "https://github.com/KevsterAmp"
    weight = 20

  [[menus.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kevin-amparado/"
    weight = 30

