baseURL = 'https://kevinamparado.com/'
languageCode = 'en-us'
title = 'Kevin Amparado'
theme = 'hugo-bearblog'

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

